project:
  type: website
  output-dir: "./docs"
  render:
    - "*.qmd"
  preview:
    port: 5133

execute:
  freeze: auto

website:
  title: "Ibn Battuta Ltd"
  description: "One-to-One Online Arabic Lessons 
Children & Adults"
#  site-url: "https://ddi-talent.github.io/website-ug-data-science/"
#  favicon: "/favicon.png"
  navbar:
    pinned: true
    background: "#2a405e"
    right:
    - text: "Home"
      file: index.qmd
    - text: "Courses"
      file: courses.qmd
    - text: "الرئيسية"
      file: index-ar.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-location: right
    css: styles-rtl.css

       