project: 
  type: website
  
website: 
  title: "Ibn Battuta Arabic Centre Ltd
One-to-One Online Arabic Lessons 
Children & Adults"
  navbar:
    left:
      -text: "Home"
       file: index.qmd
      -text: "Courses"
        file: courses.qmd
      -text: "Our Achivements!"
        file: achivements.qmd


format:
  html:
    theme: flatly
    toc: true
       